name: Test

on: [push]

jobs:
  test:
    name: Run penny tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: alsa-lib
          version: 1.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
